"""sponsors, members, leads, badge scans

Revision ID: 71d918698570
Revises: c2e4a35f16de
Create Date: 2026-09-14 13:38:26.178243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d918698570'
down_revision: Union[str, Sequence[str], None] = 'c2e4a35f16de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_name_ar', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('booth_number', sa.String(length=40), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_mobile', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('show_publicly', sa.Boolean(), nullable=False),
    sa.Column('booth_token', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booth_token')
    )
    op.create_index(op.f('ix_sponsors_event_id'), 'sponsors', ['event_id'], unique=False)
    op.create_index(op.f('ix_sponsors_status'), 'sponsors', ['status'], unique=False)
    op.create_table('sponsor_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('is_contact', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_sponsor_members_sponsor_id'), 'sponsor_members', ['sponsor_id'], unique=False)
    op.create_table('badge_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scanned_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['sponsor_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scanned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_scans_event_id'), 'badge_scans', ['event_id'], unique=False)
    op.create_index(op.f('ix_badge_scans_member_id'), 'badge_scans', ['member_id'], unique=False)
    op.create_table('sponsor_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sponsor_id', 'registration_id', name='uq_lead_sponsor_registration')
    )
    op.create_index(op.f('ix_sponsor_leads_event_id'), 'sponsor_leads', ['event_id'], unique=False)
    op.create_index(op.f('ix_sponsor_leads_registration_id'), 'sponsor_leads', ['registration_id'], unique=False)
    op.create_index(op.f('ix_sponsor_leads_sponsor_id'), 'sponsor_leads', ['sponsor_id'], unique=False)
    op.add_column('registrations', sa.Column('sponsor_consent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('sponsor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_sponsor_id'), 'users', ['sponsor_id'], unique=False)
    op.create_foreign_key(None, 'users', 'sponsors', ['sponsor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_sponsor_id'), table_name='users')
    op.drop_column('users', 'sponsor_id')
    op.drop_column('registrations', 'sponsor_consent')
    op.drop_index(op.f('ix_sponsor_leads_sponsor_id'), table_name='sponsor_leads')
    op.drop_index(op.f('ix_sponsor_leads_registration_id'), table_name='sponsor_leads')
    op.drop_index(op.f('ix_sponsor_leads_event_id'), table_name='sponsor_leads')
    op.drop_table('sponsor_leads')
    op.drop_index(op.f('ix_badge_scans_member_id'), table_name='badge_scans')
    op.drop_index(op.f('ix_badge_scans_event_id'), table_name='badge_scans')
    op.drop_table('badge_scans')
    op.drop_index(op.f('ix_sponsor_members_sponsor_id'), table_name='sponsor_members')
    op.drop_table('sponsor_members')
    op.drop_index(op.f('ix_sponsors_status'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_event_id'), table_name='sponsors')
    op.drop_table('sponsors')
    # ### end Alembic commands ###
