"""session rule, auto certificates, indexes

Revision ID: c2e4a35f16de
Revises: 3a7ecc5a360d
Create Date: 2026-09-12 14:50:16.732222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e4a35f16de'
down_revision: Union[str, Sequence[str], None] = '3a7ecc5a360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('session_rule', sa.String(length=10), server_default='overall', nullable=False))
    op.add_column('events', sa.Column('auto_issue_certificates', sa.Boolean(), server_default='true', nullable=False))
    op.create_index('ix_registrations_event_status', 'registrations', ['event_id', 'status'], unique=False)
    op.create_index('ix_scans_event_time', 'scans', ['event_id', 'scanned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scans_event_time', table_name='scans')
    op.drop_index('ix_registrations_event_status', table_name='registrations')
    op.drop_column('events', 'auto_issue_certificates')
    op.drop_column('events', 'session_rule')
    # ### end Alembic commands ###
