export const landingCopy = {
  ar: {
    home: "الرئيسية",
    events: "الفعاليات",
    about: "عن المنصة",
    journey: "رحلة المشاركة",
    faq: "الأسئلة الشائعة",
    mainSite: "موقع عيادتي",
    menu: "القائمة الرئيسية",
    skip: "انتقل إلى المحتوى",
    platform: "منصة عيادتي للتعليم الطبي المستمر",
    country: "المملكة العربية السعودية",
    brand: "فعاليات عيادتي",
    brandEn: "MY CLINIC EVENTS",
    heroEyebrow: "نلتقي على المعرفة. نجتمع للرعاية.",
    heroTitle: "معرفة تُلهم.\nورعاية ترتقي.",
    heroIntro:
      "ملتقى الممارسين الصحيين للتعلّم وتبادل الخبرات. اكتشف أيامنا العلمية ولقاءاتنا الطبية، وكن جزءًا من رحلة تطوير الرعاية الصحية في المملكة.",
    browse: "استكشف الفعاليات",
    discover: "تعرّف على المنصة",
    heroCaption: "من قلب عيادتي، إلى مستقبل الرعاية",
    heroAlt: "استقبال عيادتي في المملكة العربية السعودية",
    next: "الفعالية القادمة",
    eventDetails: "تفاصيل الفعالية",
    register: "سجّل الآن",
    pastDetails: "استعرض الفعالية",
    allEvents: "عرض جميع الفعاليات",
    medicalEducation: "التعليم الطبي المستمر",
    saudiCommunity: "مجتمع صحي في المملكة",
    scientificMeetings: "لقاءات علمية ومهنية",
    digitalExperience: "تسجيل وحضور رقمي",
    eventsEyebrow: "لقاءات تصنع أثرًا",
    eventsTitle: "فعالياتنا الطبية",
    eventsIntro:
      "اكتشف لقاءاتنا القادمة، واطّلع على أيامنا العلمية السابقة. المعرفة مستمرة، والفرص تتجدّد.",
    all: "جميع الفعاليات",
    open: "التسجيل متاح",
    past: "الفعاليات السابقة",
    ended: "فعالية سابقة",
    closed: "التسجيل مغلق",
    full: "اكتملت المقاعد",
    notPublished: "قريبًا",
    viewProgramme: "اطّلع على البرنامج",
    date: "التاريخ",
    time: "الوقت",
    venue: "المكان",
    dateTba: "يُعلن الموعد قريبًا",
    venueTba: "يُعلن المكان قريبًا",
    photoCaption: "من مرافق عيادتي",
    cme: "ساعات تعليم طبي",
    seats: "مقعد متاح",
    preview: "معاينة",
    catalogueEyebrow: "دليلك إلى فعاليات عيادتي",
    catalogueTitle: "فرص جديدة للتعلّم.\nلقاءات تستحق الحضور.",
    catalogueIntro:
      "تصفّح الفعاليات الطبية والأيام العلمية. اختر ما يناسب اهتماماتك، وتعرّف على البرنامج وساعات التعليم الطبي وتفاصيل الحضور.",
    search: "ابحث باسم الفعالية أو المكان…",
    searchLabel: "البحث في الفعاليات",
    results: "عدد الفعاليات",
    reset: "مسح البحث والفلاتر",
    noResults: "لا توجد فعاليات مطابقة",
    noResultsBody: "جرّب البحث بكلمات أخرى أو استعرض جميع الفعاليات.",
    noEvents: "نحضّر للقائنا القادم",
    noEventsBody:
      "ستظهر الفعاليات الجديدة هنا فور الإعلان عنها. يسعدنا أن تكون جزءًا من لقاءاتنا القادمة.",
    error: "تعذّر تحميل الفعاليات",
    errorBody: "يرجى المحاولة مجددًا للاطّلاع على أحدث الفعاليات.",
    retry: "إعادة المحاولة",
    aboutEyebrow: "من عيادتي، للممارس الصحي",
    aboutTitle: "نؤمن أن تطوير المعرفة\nهو بداية تطوير الرعاية.",
    aboutIntro:
      "تجمع منصة فعاليات عيادتي الممارسين الصحيين في بيئة مهنية لتبادل الخبرات ومناقشة المستجدات الطبية. لقاءات تربط المعرفة بالممارسة، وتفتح آفاقًا جديدة للتعلّم المستمر.",
    aboutAlt: "فريق الرعاية الصحية في محطة التمريض بعيادتي",
    aboutChecks: [
      "برامج علمية مرتبطة بالممارسة الطبية",
      "تواصل وتبادل خبرات بين الممارسين الصحيين",
      "تجربة رقمية من التسجيل إلى شهادة الحضور",
    ],
    aboutLink: "تعرّف على عيادتي",
    journeyEyebrow: "تجربة واضحة من البداية",
    journeyTitle: "خطوتك التالية، بكل سهولة.",
    steps: [
      {
        title: "اختر فعاليتك",
        text: "تصفّح البرنامج العلمي والمواعيد والمكان ومتطلبات الحضور، واختر ما يناسب مسارك المهني.",
        icon: "calendar",
      },
      {
        title: "أكمل تسجيلك",
        text: "سجّل بياناتك إلكترونيًا واحصل على بطاقة حضورك الشخصية مع رمز الاستجابة السريعة.",
        icon: "qr",
      },
      {
        title: "شارك واستفد",
        text: "سجّل دخولك وخروجك أثناء الفعالية، واحصل على شهادة الحضور عند استيفاء متطلباتها.",
        icon: "award",
      },
    ],
    faqEyebrow: "قبل أن تشارك",
    faqTitle: "كل ما تود معرفته.",
    faqs: [
      {
        question: "من يمكنه المشاركة في الفعاليات؟",
        answer:
          "فعالياتنا موجّهة للممارسين الصحيين. راجع صفحة كل فعالية لمعرفة الفئة المستهدفة والبرنامج العلمي وأي متطلبات خاصة بالمشاركة.",
      },
      {
        question: "هل تتوفر ساعات تعليم طبي مستمر؟",
        answer:
          "تختلف الساعات وتفاصيل الاعتماد حسب الفعالية. ستجد المعلومات ومتطلبات الحضور في صفحة الفعالية. إصدار الشهادة مرتبط باستيفاء المتطلبات المحددة.",
      },
      {
        question: "كيف أحصل على بطاقة الحضور؟",
        answer:
          "بعد إتمام التسجيل ستظهر لك بطاقة حضورك الشخصية برمز الاستجابة السريعة، وتُرسل نسخة إلى بريدك الإلكتروني. احتفظ بالبطاقة لعرضها عند الدخول والخروج.",
      },
      {
        question: "هل يمكن التسجيل في فعالية سابقة؟",
        answer:
          "الفعاليات السابقة متاحة للاطّلاع على معلوماتها وبرامجها فقط. يمكنك التسجيل في الفعاليات التي تحمل حالة «التسجيل متاح» ما دامت المقاعد متوفرة.",
      },
    ],
    ctaTitle: "لأن التعلّم لا يتوقف.",
    ctaText: "اكتشف لقاءك القادم، وامنح معرفتك مساحة جديدة للنمو.",
    footerText:
      "منصة عيادتي للفعاليات الطبية والتعلّم المستمر. نجمع المعرفة والخبرة، من أجل رعاية أفضل.",
    footerRights: "عيادتي. جميع الحقوق محفوظة.",
    footerTag: "حيث صحتك تهمنا",
    privacy: "سياسة الخصوصية",
    backTop: "العودة للأعلى",
  },
  en: {
    home: "Home",
    events: "Events",
    about: "About the platform",
    journey: "How it works",
    faq: "FAQs",
    mainSite: "My Clinic website",
    menu: "Main navigation",
    skip: "Skip to content",
    platform: "My Clinic Continuing Medical Education",
    country: "Kingdom of Saudi Arabia",
    brand: "My Clinic Events",
    brandEn: "EDUCATION & CONNECTION",
    heroEyebrow: "CONNECTED BY KNOWLEDGE. UNITED BY CARE.",
    heroTitle: "Knowledge inspires.\nCare advances.",
    heroIntro:
      "A meeting place for healthcare professionals to learn and exchange expertise. Explore our scientific days and medical events, and be part of better care across Saudi Arabia.",
    browse: "Explore events",
    discover: "About the platform",
    heroCaption: "From the heart of My Clinic. For the future of care.",
    heroAlt: "My Clinic reception in Saudi Arabia",
    next: "Next event",
    eventDetails: "Event details",
    register: "Register now",
    pastDetails: "Explore event",
    allEvents: "View all events",
    medicalEducation: "Continuing medical education",
    saudiCommunity: "A healthcare community in Saudi Arabia",
    scientificMeetings: "Scientific & professional meetings",
    digitalExperience: "Digital registration & attendance",
    eventsEyebrow: "COME TOGETHER. MOVE FORWARD.",
    eventsTitle: "Our medical events",
    eventsIntro:
      "Discover upcoming gatherings and revisit our scientific days. Learning continues, and new opportunities await.",
    all: "All events",
    open: "Registration open",
    past: "Past events",
    ended: "Past event",
    closed: "Registration closed",
    full: "Fully booked",
    notPublished: "Coming soon",
    viewProgramme: "Explore the programme",
    date: "Date",
    time: "Time",
    venue: "Venue",
    dateTba: "Date to be announced",
    venueTba: "Venue to be announced",
    photoCaption: "My Clinic facilities",
    cme: "CME hours",
    seats: "seats available",
    preview: "Preview",
    catalogueEyebrow: "YOUR GUIDE TO MY CLINIC EVENTS",
    catalogueTitle: "New perspectives.\nMeaningful connections.",
    catalogueIntro:
      "Browse medical events and scientific days. Find your interests and explore programmes, CME information, and attendance details.",
    search: "Search by event name or venue…",
    searchLabel: "Search events",
    results: "Events found",
    reset: "Clear search and filters",
    noResults: "No matching events",
    noResultsBody: "Try another search or explore all events.",
    noEvents: "Preparing for our next gathering",
    noEventsBody:
      "New events will appear here as they are announced. We look forward to welcoming you.",
    error: "Unable to load events",
    errorBody: "Please try again to see the latest events.",
    retry: "Try again",
    aboutEyebrow: "FROM MY CLINIC. FOR HEALTHCARE PROFESSIONALS.",
    aboutTitle: "Advancing knowledge.\nElevating everyday care.",
    aboutIntro:
      "My Clinic Events brings healthcare professionals together to exchange expertise and discuss medical developments. Our gatherings connect knowledge to practice and open new possibilities for continuing education.",
    aboutAlt: "Healthcare colleagues at My Clinic’s nursing station",
    aboutChecks: [
      "Scientific programmes connected to medical practice",
      "Professional connections and shared expertise",
      "A digital journey from registration to attendance certificate",
    ],
    aboutLink: "Get to know My Clinic",
    journeyEyebrow: "A CLEAR JOURNEY, FROM THE START",
    journeyTitle: "Your next step, made simple.",
    steps: [
      {
        title: "Find your event",
        text: "Explore the programme, dates, location and attendance requirements to find the right event for your professional journey.",
        icon: "calendar",
      },
      {
        title: "Save your place",
        text: "Register online and receive your personal attendance pass with a unique QR code.",
        icon: "qr",
      },
      {
        title: "Take part. Take it further.",
        text: "Scan in and out at the event, and access your attendance certificate when you meet the requirements.",
        icon: "award",
      },
    ],
    faqEyebrow: "BEFORE YOU JOIN US",
    faqTitle: "A few things to know.",
    faqs: [
      {
        question: "Who can attend the events?",
        answer:
          "Our events are designed for healthcare professionals. Check each event page for the intended audience, scientific programme, and any participation requirements.",
      },
      {
        question: "Are continuing medical education hours available?",
        answer:
          "CME hours and accreditation details vary by event. Check the event page for the confirmed information and attendance requirements. Certificates are issued when the specified requirements are met.",
      },
      {
        question: "How do I get my attendance pass?",
        answer:
          "After registration, your personal QR attendance pass will appear and a copy will be emailed to you. Keep it ready to scan when you arrive and leave.",
      },
      {
        question: "Can I register for a past event?",
        answer:
          "Past events remain available to explore their information and programmes. Registration is available for events marked ‘Registration open’ while seats remain.",
      },
    ],
    ctaTitle: "Because learning never stops.",
    ctaText: "Discover your next event. Make room for your next perspective.",
    footerText:
      "My Clinic’s platform for medical events and continuing education. Bringing knowledge and experience together for better care.",
    footerRights: "My Clinic. All rights reserved.",
    footerTag: "Where your health matters",
    privacy: "Privacy policy",
    backTop: "Back to top",
  },
} as const;
